#!/usr/bin/env python3
"""Build the blog index page at docs/index.html listing all papers.

Usage:
    python3 scripts/build_blog_index.py

Reads each papers/<slug>/card.json and produces a card-grid landing page.
"""
from __future__ import annotations

import json
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAPERS = ROOT / "papers"
OUT = ROOT / "docs" / "index.html"


def main() -> None:
    cards = []
    for card_path in sorted(PAPERS.glob("*/card.json")):
        c = json.loads(card_path.read_text(encoding="utf-8"))
        slug = c.get("slug", card_path.parent.name)
        cards.append({
            "slug": slug,
            "title": c.get("title", slug),
            "affiliation": c.get("affiliation", ""),
            "date": c.get("date", ""),
            "arxiv": c.get("arxiv", ""),
            "one_liner": c.get("one_liner", ""),
            "category": c.get("category", ""),
            "tags": c.get("tags", []),
            "cover_fig": next((f["image_path"] for f in c.get("figures", [])
                                if f.get("importance") == "key"), None),
        })

    cards_html = []
    for c in cards:
        cover = f'<img src="../papers/{c["slug"]}/{c["cover_fig"]}" alt="cover" loading="lazy"/>' if c["cover_fig"] else ""
        tags = "".join(f"<span class='tag'>{escape(t)}</span>" for t in c["tags"][:4])
        cards_html.append(f"""
        <a class="card" href="../papers/{c['slug']}/index.html">
          {cover}
          <div class="card-body">
            <span class="cat">{escape(c['category'])}</span>
            <h3>{escape(c['title'])}</h3>
            <p class="one-liner">{escape(c['one_liner'])}</p>
            <div class="meta">
              <span>{escape(c['affiliation'])}</span> · <span>{escape(c['date'])}</span> · arXiv:{escape(c['arxiv'])}
            </div>
            <div class="tags">{tags}</div>
          </div>
        </a>
        """)

    html = f"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Paper Podcast — 论文深度解读</title>
<style>
:root {{
  --bg:#fafbfa; --paper:#fff; --ink:#17201c; --muted:#65706b;
  --line:#dfe6e2; --accent:#0f766e; --soft:#eaf5f2; --dark:#111614;
}}
* {{ box-sizing:border-box; }}
body {{ margin:0; background:var(--bg); color:var(--ink);
  font-family:-apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",Arial,sans-serif;
  line-height:1.6; }}
header.hero {{ background:var(--dark); color:#e8f1ee; padding:60px 40px 40px; text-align:center; }}
header.hero h1 {{ margin:0 0 10px; font-size:34px; }}
header.hero p {{ color:#9fb3ac; max-width:640px; margin:8px auto 0; font-size:15px; }}
main {{ max-width:1100px; margin:0 auto; padding:32px 24px 80px; }}
.grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(320px,1fr)); gap:24px; }}
.card {{ display:block; background:var(--paper); border:1px solid var(--line);
  border-radius:12px; overflow:hidden; text-decoration:none; color:inherit;
  transition:transform .15s, box-shadow .15s; }}
.card:hover {{ transform:translateY(-3px); box-shadow:0 8px 24px rgba(0,0,0,0.08); }}
.card img {{ width:100%; height:180px; object-fit:cover; border-bottom:1px solid var(--line); }}
.card-body {{ padding:18px 20px; }}
.card .cat {{ display:inline-block; background:var(--soft); color:var(--accent);
  font-size:11px; font-weight:700; padding:3px 10px; border-radius:4px; text-transform:uppercase; }}
.card h3 {{ font-size:17px; line-height:1.35; margin:10px 0 8px; }}
.card .one-liner {{ color:var(--muted); font-size:13px; margin:0 0 10px; }}
.card .meta {{ font-size:12px; color:var(--muted); }}
.tags {{ margin-top:10px; }}
.tag {{ display:inline-block; background:#f0f2f1; color:var(--muted);
  font-size:11px; padding:2px 8px; border-radius:3px; margin-right:4px; }}
.footer {{ text-align:center; color:var(--muted); padding:40px; font-size:13px; }}
@media (max-width:600px) {{
  .grid {{ grid-template-columns:1fr; }}
  header.hero {{ padding:40px 20px; }}
}}
</style>
</head>
<body>
<header class="hero">
  <h1>Paper Podcast</h1>
  <p>研究论文深度解读：每篇产出结构化卡片、架构图、口播稿、HTML 视图、音频播客。目标是一个没看过论文的人，听完就能在脑子里建出结构。</p>
</header>
<main>
  <div class="grid">
    {''.join(cards_html)}
  </div>
</main>
<div class="footer">
  generated by <a href="https://github.com" style="color:var(--accent);">paper-podcast skill</a> ·
  <a href="../skill/SKILL.md" style="color:var(--accent);">skill 文档</a>
</div>
</body>
</html>
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(html, encoding="utf-8")
    print(f"OK -> {OUT}  ({len(cards)} papers)")


if __name__ == "__main__":
    main()
